### ISSUE TITLE
Prometheus Probe CRD doesn't probe targets

### ISSUE THREAD

**Issue by rjonala** [thaum-xyz/ankhmorpork#49]
I am using Prometheus Probe CRD and Blackbox exporter to scrape static targets. But, when I checked in Blackbox exporter, I don't see specified targets being probed at all.

I was able to probe targets using Blackbox exporter and additionalScrapeConfigs in values file of Prometheus exporter but it doesn't work with Probe CRD.

Here is my Probe custom object config,

```
kind: Probe
metadata:
  name: probe-crd
  namespace: prometheus
spec:
  jobName: probe-crd
  prober:
    url: prometheus-blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - https://www.google.com
```
Blackbox exporter service is running on port 9115. Can someone please let me know what I am missing here?
